backend:
  name: git-gateway
  branch: branch-b

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "docs"
    label: "Docs"
    folder: "Docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
